services:
  web:
    image: projectname:1.0
    build: .
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:
    - .:/code   
    environment:
      - POSTGRES_USER=gisuser
      - POSTGRES_PASS=password
      - POSTGRES_DB=gis
    ports:
    # - "127.0.0.1:6060:6060/udp"
      - target: 8000
        host_ip: 127.0.0.1
        published: 8000
        protocol: tcp
        mode: host